"""add category to client_note

Revision ID: 041993142c1c
Revises: 055d150eea28
Create Date: 2026-02-20 00:35:53.659510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041993142c1c'
down_revision: Union[str, None] = '055d150eea28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_note', sa.Column('category', sa.String(), server_default='note', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_note', 'category')
    # ### end Alembic commands ###
